# Generated by Django 3.2.12 on 2022-02-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bank_account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=10, verbose_name='Saldo de cuenta'),
            preserve_default=False,
        ),
    ]
