# Generated by Django 3.2.12 on 2022-02-12 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bank_account', '0002_bank_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='account_number',
            field=models.CharField(max_length=255, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo'),
        ),
    ]
