# Generated by Django 3.2.12 on 2022-02-22 22:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Banco',
                'verbose_name_plural': 'Bancos',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad')),
                ('account_type', models.CharField(max_length=255, verbose_name='Tipo de movimiento')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
            },
        ),
        migrations.CreateModel(
            name='Bank_account',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('account_number', models.CharField(max_length=255, unique=True, verbose_name='Número de cuenta')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo')),
                ('account_type', models.CharField(max_length=255, verbose_name='Tipo de cuenta')),
                ('id_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banks', to='banks.bank', verbose_name='Banco')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bankaccounts', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Cuenta de Banco',
                'verbose_name_plural': 'Cuentas de Banco',
            },
        ),
    ]
