# Generated by Django 3.2.12 on 2022-03-04 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_auto_20220303_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='account_type',
            new_name='movement_type',
        ),
    ]
