# Generated by Django 3.2.12 on 2022-03-04 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_rename_account_type_movement_movement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movement',
            old_name='Bank_account',
            new_name='bank_account',
        ),
    ]
