# Generated by Django 3.2.12 on 2022-03-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0004_rename_bank_account_movement_bank_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo'),
        ),
    ]
