# Generated by Django 3.2.12 on 2022-03-17 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0005_alter_bank_account_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank_account',
            name='account_number',
            field=models.IntegerField(unique=True, verbose_name='Número de cuenta'),
        ),
    ]
