# Generated by Django 3.2.12 on 2022-03-17 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0006_alter_bank_account_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de cuenta',
                'verbose_name_plural': 'Tipos de cuenta',
            },
        ),
        migrations.RemoveField(
            model_name='bank_account',
            name='account_type',
        ),
        migrations.AddField(
            model_name='bank_account',
            name='id_account_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='account_types', to='banks.account_type', verbose_name='Tipo de cuenta'),
            preserve_default=False,
        ),
    ]
