# Generated by Django 3.2.12 on 2022-03-17 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0007_auto_20220316_1915'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account_type',
            options={'verbose_name': 'Tipo de cuenta', 'verbose_name_plural': 'Tipo de cuentas'},
        ),
        migrations.AlterField(
            model_name='bank_account',
            name='id_account_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts_type', to='banks.account_type', verbose_name='Tipo de cuenta'),
        ),
    ]
