# Generated by Django 3.2.12 on 2022-03-19 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0009_alter_bank_account_account_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movement_type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Tipo de movimiento',
                'verbose_name_plural': 'Tipo de movimientos',
            },
        ),
        migrations.AlterField(
            model_name='movement',
            name='movement_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_type', to='banks.movement_type', verbose_name='Tipo de movimiento'),
        ),
    ]
