# Generated by Django 3.2.12 on 2022-03-25 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0010_auto_20220318_2221'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='available_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo disponible'),
        ),
    ]
